version: '3'

services:
  db:
    image: mysql:5.7
      # ports:
    # - ${IP}:3306:3306 # change ip if required
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
    networks:
      - wp

  wordpress:
    ports:
      - "8000:80"
    depends_on:
      - db
    image: wordpress:latest
    volumes: ["./html:/var/www/html"]
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wp
networks:
  wp:
volumes:
  db_data:
